### ISSUE TITLE
Review Plugins used

### ISSUE THREAD

**Issue by SteveBarnett** [CTFEDs/RapeCrisisCapeTownTrust#18]
What can be swapped out for static code (since it doesn't change often / at all), and what can just be removed?

**Comment by Archie22is** [comment]
# Final Plugins Review

**[high priority plugins]**
- Regenerate Thumbnails 
- Lizatom Shortcodes (or a similar plugin will do the job - shortcodes have advantages]
- BackupBuddy (if it works, we can keep it. I use backwpup)
- 1000 hearts
- Foobar Notifications (if there is a need)

**[a plugin or custom code can work]**
- uSquare (must be removed when creating the new WordPress responsive theme)

**[good old code is better]**
- Newsletter Tycoon (since the plan is to switch to Mailchimp, we can create a custom subscribe form) or we can use the MailChimp List Subscribe Form plugin. 
- WordPress Mobile Pack (no need for this once we redesign the site)
- Thumbnail Gallery (A custom gallery can be created, or the default WordPress gallery can be enhanced to deliver what the client desires)
- Social Network Tabs (good old code please)
- Social Media Icons Widget (good old code please)
- NextGen Gallery

**[must delete]**
- Akismet
- Bounce Grab Lite
- Hello Dolly
- WordPress Importer (no need for this)
- Styled Facebook Like Box (it goes without saying - we can do better)
- Page peel (what is that)
- 5 Seconds Google maps

**Comment by justinslack** [comment]
# Final Plugins Review - updated 19 July

**[high priority plugins]**
- Regenerate Thumbnails 
- Lizatom Shortcodes (or a similar plugin will do the job - shortcodes have advantages]
- BackupBuddy 
- 1000 hearts - (needs work)

**[a plugin or custom code can work]**
- uSquare (must be removed when creating the new WordPress responsive theme) Tricky one this as it displays staff members in a very specific way

**[good old code is better]**
- Newsletter Tycoon (since the plan is to switch to Mailchimp, we can create a custom subscribe form) or we can use the MailChimp List Subscribe Form plugin. 
- WordPress Mobile Pack (no need for this once we redesign the site)
- Thumbnail Gallery (A custom gallery can be created, or the default WordPress gallery can be enhanced to deliver what the client desires)
- Social Network Tabs (good old code please)
- Social Media Icons Widget (good old code please)
- NextGen Gallery

**[must delete]**
- Akismet (alternate spam protection)
- Bounce Grab Lite
- Hello Dolly
- WordPress Importer (no need for this)
- Styled Facebook Like Box (it goes without saying - we can do better)
- Page peel (what is that)
- 5 Seconds Google maps
- Foobar Notifications (if there is a need)
